workflows:
  flutter-ci-cd:
    name: Flutter CI/CD (with your build steps)
    max_build_duration: 60
    instance_type: mac_mini_m1  # Add this for better performance
    
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
          source: true
    
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    
    scripts:
      # Step 1: Clean and get dependencies
      - name: Flutter clean & pub get
        script: |
          flutter clean
          flutter pub get

      # Step 2: iOS Build (Fixed version)
      - name: Build iOS (Runner.app → IPA)
        script: |
          echo "Running Pre build commands for iOS"
          cd ios
          pod install
          cd ..
          echo "Building iOS in release mode..."
          flutter build ios --release --no-codesign -t lib/main.dart
          mkdir -p Payload
          cp -R ./build/ios/iphoneos/Runner.app Payload/
          cd Payload
          zip -r ../Payload.ipa .
          cd ..
          rm -rf Payload

      # Step 3: Android Build
      - name: Build Android (Release APK)
        script: |
          echo "Building Android..."
          flutter build apk --release -t lib/main.dart
          cp ./build/app/outputs/flutter-apk/app-release.apk miracle_meditation.apk

      # Step 4: Dummy Deployment
      - name: Dummy Deployment
        script: |
          echo "Pretending to upload IPA to Diawi..."
          sleep 2
          echo "Pretending to upload APK to Play Store..."
          sleep 2
          echo "✅ Dummy deployment finished!"

    artifacts:
      - Payload.ipa
      - miracle_meditation.apk
    
    publishing:
      email:
        recipients:
          - your-email@example.com
        notify:
          success: true
          failure: true